// generated by "sampctl package generate"

#include "drift-detection.inc"

main() {
	
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/drift", true))
	{
		new Float:x, Float:y, Float:z;
		GetPlayerPos(playerid, x, y, z);
		PutPlayerInVehicle(playerid, CreateVehicle(411, x, y, z+1, 0, 211, 1, -1), 0);
		Drift::EnableDetection(playerid);
		Drift::EnableDamageCheck(playerid);
	}
	return true;
}
public OnPlayerDriftStart(playerid)
{
	GameTextForPlayer(playerid, "~g~Drift Started!", 1000, 6);
	return true;
}
public OnPlayerDriftUpdate(playerid, Float: drift_angle, Float: speed)
{
	new message[128];
	format(message, sizeof message, "~g~Drifting!!~n~~b~Angle:~r~ %0.1f~n~~b~Speed: ~r~%0.1f", drift_angle, speed);
	GameTextForPlayer(playerid, message, 1000, 6);
	return true;
}
public OnPlayerDriftEnd(playerid, reason, Float: distance, time)
{
	new message[128];
	format(message, sizeof message, "~g~Drift End!!~n~~b~Reason: ~r~%i~n~~b~Distance:~r~ %0.1f~n~~b~Time: ~r~%d", reason, distance, time / 1000);
	GameTextForPlayer(playerid, message, 1000, 6);
	return true; 
}